# NOTE: update this with your service name
service: internn-serverless

# Create an optimized package for our functions
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables
  - serverless-domain-manager

custom:
  customDomain:
    domainName: www.internn.co.uk
    basePath: ""
    stage: ${self:custom.myStage}
    enabled: ${self:custom.useDomain.${self:custom.myStage}}
  myStage: ${opt:stage, self:provider.stage}
  useDomain:
    dev: false
    prod: true

provider:
  name: aws
  runtime: nodejs10.x
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ses:SendEmail"
      Resource: ["*"]
  stage: dev
  region: eu-west-1 # Set to Ireland region. Original was us-east-1
  # To load environment variables externally
  # rename env.example to .env and uncomment
  # the following line. Also, make sure to not
  # commit your .env.
  #
  #environment:
  #  SAMPLE_ENV_VAR: ${env:SAMPLE_ENV_VAR}

functions:
  contactMailer:
    handler: handler.contactMailer
    events:
      - http:
          path: contact-us
          method: post
